mkdir "C:\projects\rematrix-filter\obs-studio\"
mkdir "C:\projects\rematrix-filter\obs-studio\obs-plugins"
mkdir "C:\projects\rematrix-filter\obs-studio\obs-plugins\32bit"
mkdir "C:\projects\rematrix-filter\obs-studio\obs-plugins\64bit"
mkdir "C:\projects\rematrix-filter\obs-studio\data\"
mkdir "C:\projects\rematrix-filter\obs-studio\data\obs-plugins\"
mkdir "C:\projects\rematrix-filter\obs-studio\data\obs-plugins\rematrix-filter\"
mkdir "C:\projects\rematrix-filter\obs-studio\data\obs-plugins\rematrix-filter\locale\"
robocopy "C:\projects\obs-studio\build32\rundir\Release\obs-plugins\32bit" "C:\projects\rematrix-filter\obs-studio\obs-plugins\32bit" "rematrix-filter.*"
robocopy "C:\projects\obs-studio\build64\rundir\Release\obs-plugins\64bit" "C:\projects\rematrix-filter\obs-studio\obs-plugins\64bit" "rematrix-filter.*"
robocopy "C:\projects\rematrix-filter\data\locale" "C:\projects\rematrix-filter\obs-studio\data\obs-plugins\rematrix-filter\locale" "*.*"
7z a C:\projects\rematrix-filter\obs-studio.zip C:\projects\rematrix-filter\obs-studio*
