mkdir "C:\projects\rematrix-filter\build\"
mkdir "C:\projects\rematrix-filter\build\obs-plugins"
mkdir "C:\projects\rematrix-filter\build\obs-plugins\32bit"
mkdir "C:\projects\rematrix-filter\build\obs-plugins\64bit"
mkdir "C:\projects\rematrix-filter\build\data\"
mkdir "C:\projects\rematrix-filter\build\data\obs-plugins\"
mkdir "C:\projects\rematrix-filter\build\data\obs-plugins\rematrix-filter\"
mkdir "C:\projects\rematrix-filter\build\data\obs-plugins\rematrix-filter\locale\"
robocopy "C:\projects\obs-studio\build32\rundir\RelWithDebInfo\obs-plugins\32bit" "C:\projects\rematrix-filter\build\obs-plugins\32bit" "rematrix-filter.*"
robocopy "C:\projects\obs-studio\build64\rundir\RelWithDebInfo\obs-plugins\64bit" "C:\projects\rematrix-filter\build\obs-plugins\64bit" "rematrix-filter.*"
robocopy "C:\projects\rematrix-filter\data\locale" "C:\projects\rematrix-filter\build\data\obs-plugins\rematrix-filter\locale" "*.*"
7z a C:\projects\rematrix-filter\build.zip C:\projects\rematrix-filter\build*
